/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://llkqfml6dbcnhgzui5ixnylk7e.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-adfpr3lfyrguzpkt7xliosfjti",
    "aws_cognito_identity_pool_id": "eu-north-1:3241cbf4-3d86-484b-a3f1-e65d6b4c8e1a",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_Q96jKFQ5a",
    "aws_user_pools_web_client_id": "5m6iac3ubcep179lcrqm4ueaic",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "instaclonev2d8dbdf91b91a4b4da8ed690207abaf6291744-staging",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
